[project]
name = "TexNano"
version = "0.1.0"
description = "TexNano"
channels = ["conda-forge"]

platforms = ["win-64"]

[tasks]
start = "python test.py"

[dependencies]
python = ">=3.12.1,<3.13"
numpy = ">=1.26.4,<1.27"
optuna = ">=3.5.0,<3.6"
pandas = ">=2.2.0,<2.3"
wandb = ">=0.16.3,<0.17"
scikit-learn = ">=1.4.0,<1.5"
matplotlib = ">=3.8.2,<3.9"
tensorboard = ">=2.15.1,<2.16"
